{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "z-courier.secretName" . }}
  labels:
    {{- include "z-courier.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.authProviderSharedToken }}: {{ .Values.secret.values.authProviderSharedToken | quote }}
  {{ .Values.secret.keys.internalHMACSecret }}: {{ .Values.secret.values.internalHMACSecret | quote }}
  {{ .Values.secret.keys.peerHMACSecret }}: {{ .Values.secret.values.peerHMACSecret | quote }}
  {{ .Values.secret.keys.postgresPassword }}: {{ .Values.secret.values.postgresPassword | quote }}
  {{ .Values.secret.keys.redisPassword }}: {{ .Values.secret.values.redisPassword | quote }}
  {{ .Values.secret.keys.upstreamInternalToken }}: {{ .Values.secret.values.upstreamInternalToken | quote }}
  {{- if eq .Values.downlink.terminal.publisher.type "http" }}
  {{ .Values.secret.keys.terminalWebhookHMACSecret }}: {{ .Values.secret.values.terminalWebhookHMACSecret | quote }}
  {{- end }}
{{- end }}
