apiVersion: v1
kind: Service
metadata:
  name: {{ include "z-courier.headlessServiceName" . }}
  labels:
    {{- include "z-courier.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless-service
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: internal
      port: {{ .Values.internalService.port }}
      targetPort: internal
      protocol: TCP
  selector:
    {{- include "z-courier.selectorLabels" . | nindent 4 }}
