location = /healthz {
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location = /readyz {
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location = /metrics {
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location = /internal/push {
    limit_except POST {
        deny all;
    }
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location = /internal/push/batch {
    limit_except POST {
        deny all;
    }
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location = /internal/cluster/push {
    limit_except POST {
        deny all;
    }
    include /etc/nginx/zcourier/proxy-common.conf;
    proxy_pass http://zcourier_machine;
}

location / {
    return 404;
}
