global:
  resolve_timeout: 5m

route:
  receiver: z-courier-webhook
  group_by:
    - alertname
    - component
    - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: z-courier-webhook-critical
      matchers:
        - severity="critical"
      repeat_interval: 1h

receivers:
  - name: z-courier-webhook
    webhook_configs:
      - url: http://alert-webhook.example.internal/alertmanager
        send_resolved: true

  - name: z-courier-webhook-critical
    webhook_configs:
      - url: http://alert-webhook.example.internal/alertmanager/critical
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - job
      - instance
